version: "3.9"
services:
  mysql:
    image: "mariadb:10.6"
    restart: always
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - ./db_data:/var/lib/mysql
      - ./90-extra.cnf:/etc/mysql/mariadb.conf.d/90-extra.cnf
  powerdns:
    #image: "powerdns/pdns-auth-45"
    build:
      context: ../pdns-auth-mysql
      dockerfile: Dockerfile
      args:
        buildno: v0.0.1
    restart: always
    env_file:
      - .env
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "8081:8081"
    depends_on:
      - "mysql"
    # logging:
    #   driver: json-file
    #   options:
    #     max-size: 50m
  powerdns-admin:
    image: "ngoduykhanh/powerdns-admin:0.2.3"
    restart: always
    env_file:
      - .env
    ports:
      - "9191:80"
    depends_on:
      - "mysql"
    logging:
      driver: json-file
      options:
        max-size: 50m
