version: "3.3"
services:
  db:
    image: "mariadb:10.6"
    restart: unless-stopped
    env_file:
      - .env_server
    ports:
      - "3306:3306"
    command:
      - "--server-id=${MYSQL_SERVER_ID}"
      - "--log_bin=master-bin"
      - "--binlog-format=MIXED"
      - "--log_slave_updates=on"
    logging:
      driver: json-file
      options:
        max-size: 50m
  powerdns:
    build:
      context: ../pdns-auth-mysql
      dockerfile: Dockerfile
      args:
        buildno: v0.0.1
    restart: unless-stopped
    env_file:
      - .env_server
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "8081:8081"
    depends_on:
      - "db"
    logging:
      driver: json-file
      options:
        max-size: 50m
  db-admin:
    image: "mariadb:10.6"
    restart: unless-stopped
    env_file:
      - .env_admin
    command:
      - "--server-id=${MYSQL_SERVER_ID}"
      - "--log_bin=master-bin"
      - "--binlog-format=MIXED"
      - "--log_slave_updates=on"
    logging:
      driver: json-file
      options:
        max-size: 50m
  powerdns-admin:
    image: "ngoduykhanh/powerdns-admin:0.2.3"
    restart: unless-stopped
    env_file:
      - .env_admin
    ports:
      - target: 80
        published: 9191       # ${ADMIN_WEB_PORT:-80}
        protocol: tcp
    depends_on:
      - "db-admin"
    logging:
      driver: json-file
      options:
        max-size: 50m
