version: "3.9"
services:
  mysql:
    image: "mariadb:10.6"
    restart: always
    env_file:
      - .env
    volumes:
      - ./90-extra.cnf:/etc/mysql/mariadb.conf.d/90-extra.cnf
  powerdns:
    build:
      context: ../pdns-auth-mysql
      dockerfile: Dockerfile
      args:
        buildno: v0.0.1
    restart: always
    env_file:
      - .env
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    depends_on:
      - "mysql"
