version: "2.2"
services:
  db:
    image: "mariadb:10.6"
    restart: always
    env_file:
      - .env
    command:
      - "--server-id=${MYSQL_SERVER_ID}"
      - "--log_bin=slave-bin"
      - "--log_slave_updates=on"
      - "--binlog-format=MIXED"
      - "--replicate-ignore-db=mysql"
    logging:
      driver: json-file
      options:
        max-size: 50m
  powerdns:
    build:
      context: ../pdns-auth-mysql
      dockerfile: Dockerfile
      args:
        buildno: v0.0.1
    restart: always
    env_file:
      - .env
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    depends_on:
      - "db"
    logging:
      driver: json-file
      options:
        max-size: 50m
